[package]
name = "tikus"
version = "0.0.0"
edition = "2024"

[dependencies]
glam = "0.30.8"
indicatif = { version = "0.18.0", features = ["rayon"] }
itertools = "0.14.0"
rand = "0.9.2"
rand_xoshiro = "0.7.0"
rayon = "1.11.0"
