[package]
name = "tikus"
version = "0.0.0"
edition = "2024"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1

[dependencies]
glam = "0.30.8"
indicatif = { version = "0.18.0", features = ["rayon"] }
rand = "0.9.2"
rand_pcg = "0.9.0"
rayon = "1.11.0"
